import type { Product } from "@/lib/pos/types";

// Mock catalog — replaced by real Supabase rows in DD-55+ once creds land.
// cost_satang is a realistic landed cost (~45-55% of retail) so margin reports
// and the event-setup "reserved warehouse value" show meaningful demo numbers.
export const mockProducts: Product[] = [
  {
    id: "p-001",
    workspace_id: "demo-ws",
    sku: "DEMO-001",
    name: "Cat Hoodie",
    category: "apparel",
    price_satang: 89000,
    cost_satang: 42000,
    shipping_fee_satang: 5000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 30,
  },
  {
    id: "p-002",
    workspace_id: "demo-ws",
    sku: "DEMO-002",
    name: "Catnip Toy",
    category: "toys",
    price_satang: 19000,
    cost_satang: 7000,
    shipping_fee_satang: 3000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 100,
  },
  {
    id: "p-003",
    workspace_id: "demo-ws",
    sku: "DEMO-003",
    name: "Sticker Pack · Brown",
    category: "accessories",
    price_satang: 9000,
    cost_satang: 2500,
    shipping_fee_satang: 2000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 200,
  },
  {
    id: "p-004",
    workspace_id: "demo-ws",
    sku: "DEMO-004",
    name: "Premium Cat Treats",
    category: "food",
    price_satang: 29000,
    cost_satang: 14000,
    shipping_fee_satang: 5000,
    send_later_enabled: false,
    is_active: true,
    image_path: null,
    current_qty: 4, // low-stock visual
  },
  {
    id: "p-005",
    workspace_id: "demo-ws",
    sku: "DEMO-005",
    name: "Brushed Cat Bed",
    category: "home",
    price_satang: 149000,
    cost_satang: 72000,
    shipping_fee_satang: 12000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 0, // soldout visual
  },
  {
    id: "p-006",
    workspace_id: "demo-ws",
    sku: "DEMO-006",
    name: "Tuna Pouch · Salmon · Chicken trio",
    category: "food",
    price_satang: 39000,
    cost_satang: 18000,
    shipping_fee_satang: 4000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 18,
  },
  {
    id: "p-007",
    workspace_id: "demo-ws",
    sku: "DEMO-007",
    name: "Sticker Pack · Black",
    category: "accessories",
    price_satang: 9000,
    cost_satang: 2500,
    shipping_fee_satang: 2000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 180,
  },
  {
    id: "p-008",
    workspace_id: "demo-ws",
    sku: "DEMO-008",
    name: "Cat Scarf · Beige",
    category: "apparel",
    price_satang: 49000,
    cost_satang: 22000,
    shipping_fee_satang: 5000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 12,
  },
];
