// Pre-built sample catalog so users can populate their demo with one click
// instead of typing 6+ products by hand. Replaced by Supabase seed data
// (database/seed.sql) once real workspaces are wired.

import type { Product } from "@/lib/pos/types";

export const SAMPLE_CATALOG: Array<Omit<Product, "id">> = [
  {
    workspace_id: "demo-workspace",
    sku: "CAT-HOOD",
    name: "Cat Hoodie · Brown",
    category: "apparel",
    price_satang: 89000,
    shipping_fee_satang: 5000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 30,
  },
  {
    workspace_id: "demo-workspace",
    sku: "CAT-NIP",
    name: "Catnip Toy",
    category: "toys",
    price_satang: 19000,
    shipping_fee_satang: 3000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 100,
  },
  {
    workspace_id: "demo-workspace",
    sku: "CAT-STK-BR",
    name: "Sticker Pack · Brown",
    category: "accessories",
    price_satang: 9000,
    shipping_fee_satang: 2000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 200,
  },
  {
    workspace_id: "demo-workspace",
    sku: "CAT-STK-BK",
    name: "Sticker Pack · Black",
    category: "accessories",
    price_satang: 9000,
    shipping_fee_satang: 2000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 200,
  },
  {
    workspace_id: "demo-workspace",
    sku: "CAT-TREAT",
    name: "Premium Cat Treats · Tuna",
    category: "food",
    price_satang: 29000,
    shipping_fee_satang: 5000,
    send_later_enabled: false,
    is_active: true,
    image_path: null,
    current_qty: 50,
  },
  {
    workspace_id: "demo-workspace",
    sku: "CAT-BED",
    name: "Brushed Cat Bed · Cream",
    category: "home",
    price_satang: 149000,
    shipping_fee_satang: 12000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 10,
  },
  {
    workspace_id: "demo-workspace",
    sku: "CAT-SCARF",
    name: "Cat Scarf · Beige",
    category: "apparel",
    price_satang: 49000,
    shipping_fee_satang: 5000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 12,
  },
  {
    workspace_id: "demo-workspace",
    sku: "CAT-MUG",
    name: "Cat Coffee Mug",
    category: "home",
    price_satang: 35000,
    shipping_fee_satang: 7000,
    send_later_enabled: true,
    is_active: true,
    image_path: null,
    current_qty: 18,
  },
];
